apiVersion: kyverno.io/v2
kind: ClusterCleanupPolicy
metadata:
  name: clean-bare-pods
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kyverno-policies
  annotations:
    policies.kyverno.io/title: Cleanup Bare Pods
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/minversion: 1.10.0
    policies.kyverno.io/description: >-
      Removes bare Pods (not owned by a controller) that may have been
      created manually for debugging. Excludes system namespaces.
spec:
  match:
    any:
      - resources:
          kinds:
            - Pod
  exclude:
    any:
      - resources:
          namespaces:
            - kube-system
            - kube-public
            - kube-node-lease
            - kyverno
            - argocd
  conditions:
    all:
      - key: "{{ target.metadata.ownerReferences[] || `[]` }}"
        operator: Equals
        value: []
  schedule: "*/5 * * * *"