apiVersion: v2
name: kyverno-policies
description: Helm Chart for Kyverno Policies
type: application
version: 1.0.0
dependencies:
  - name: kyverno-policies
    version: "3.7.1"
    repository: https://kyverno.github.io/kyverno/
