apiVersion: v2
name: kyverno
description: Kyverno policy engine for Kubernetes
type: application
version: 1.0.0
dependencies:
  - name: kyverno
    version: "3.7.0"
    repository: "https://kyverno.github.io/kyverno"
